name: Assemble Taro Android Apk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  fetch-shell-project:
    runs-on: ubuntu-latest
    steps:
      - name: Fecth Taro Shell Project
      - uses: actions/checkout@v2
        with:
          repository: 4332weizi/taro-native-shell
      - name: into shell project
        run: |
          cd taro-native-shell
  build-android:
    needs: fetch-shell-project
    runs-on: ubuntu-latest
    steps: 
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/