name: Assemble Taro Android Apk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-taro:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install yarn dependencies
        run: |
          yarn install
      - name: Build Taro JS Bundle
        run: |
          yarn build:rn-android
      - name: Upload Taro Products
        uses: actions/upload-artifact@v2
        with:
          name: taro-android-products
          path: dist/rn/android/
  build-android:
    needs: build-taro
    runs-on: ubuntu-latest
    steps: 
      - name: Fecth Taro Shell Project
        uses: actions/checkout@v2
        with:
          repository: 4332weizi/taro-native-shell
      - name: Install yarn dependencies
        run: |
          yarn install
      - name: Change Directory to android 
        run: |
          cd android
      - name: Build Android Release
        run: |
          ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/