name: Assemble Taro Android Apk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-taro:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          yarn install
      - name: Build Taro JS Bundle
        run: |
          yarn build:rn-android
      - name: Upload Taro Products
        uses: actions/upload-artifact@v1
        with:
          name: index.android.bundle
          path: dist/rn/android/
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/