name: Assemble Taro Android Apk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-taro:
    runs-on: ubuntu-latest
    steps: 
      - name: Fetch Project
        uses: actions/checkout@v2
      - name: Fetch Taro Shell Project
        uses: actions/checkout@v2
        with:
          repository: 4332weizi/taro-native-shell
          ref: 0.63.2_origin
          path: ShellProject
      - name: Cache node_modules
        uses: actions/cache
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules
          restore-keys: ${{ runner.os }}-node_modules
      - name: Get Yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Yarn Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          yarn install
      - name: Link node_modules
        run: |
          ln -s $PWD/node_modules $PWD/ShellProject/node_modules
      - name: Build Taro JS Bundle
        run: |
          yarn build:rn-android
      - name: Upload Taro Products
        uses: actions/upload-artifact@v2
        with:
          name: taro-android-products
          path: dist/rn/android/
      - name: Move Taro JS Bund
        run: |
          mv ./dist/rn/android/index.android.bundle ./ShellProject/android/app/src/main/assets/index.android.bundle
          rsync -a ./dist/rn/android/ ./ShellProject/android/app/src/main/res/
      - name: Cache Gradle
        uses: actions/cache@v2
        env:
          cache-name: gradle-cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: build
        if: steps.gradle-cache.outputs.cache-hit != 'true'
        run: |
          cd ./ShellProject/android && cat app/build.gradle && ./gradlew build
      - name: Build Android Debug
        run: |
          cd ./ShellProject/android && ./gradlew assembleDebug
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: $PWD/ShellProject/android/app/build/outputs/apk/debug/